// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $api_getTelemetry from "./routes/api/getTelemetry.ts";
import * as $api_shutdown from "./routes/api/shutdown.ts";
import * as $controls_index from "./routes/controls/index.tsx";
import * as $docs_index from "./routes/docs/index.tsx";
import * as $index from "./routes/index.tsx";
import * as $Navbar from "./islands/Navbar.tsx";
import * as $PDU from "./islands/PDU.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/api/getTelemetry.ts": $api_getTelemetry,
    "./routes/api/shutdown.ts": $api_shutdown,
    "./routes/controls/index.tsx": $controls_index,
    "./routes/docs/index.tsx": $docs_index,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Navbar.tsx": $Navbar,
    "./islands/PDU.tsx": $PDU,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
